### ISSUE TITLE
Sporadically throwing IllegalStateException due to HttpClient

### ISSUE THREAD

**Issue by ahmetb** [notnoop/java-c2dm#8]
Sometimes my call to C2DM library throws exception:

**IllegalStateException occured : Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.**

Here's the full stack trace:

```
Caused by: java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
    at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:216)
    at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:190)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:401)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
    at com.notnoop.c2dm.internal.C2DMServiceImpl.push(C2DMServiceImpl.java:59)
    at com.notnoop.c2dm.internal.AbstractC2DMService.push(AbstractC2DMService.java:76)
```

I'll look what can I do to fix or a workaround. Just leaving this here for other people who might hit this issue in the future.

**Comment by ahmetb** [comment]
project is dead; rest in pepperoni
